# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qmlpackagemanager

# >> macros
# << macros

Summary:    Package Manager UI for Nemo
Version:    0.2.2
Release:    1
Group:      Applications/System
License:    LGPLv2.1
URL:        https://github.com/nemomobile/qmlpackagemanager
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlpackagemanager.yaml
Requires:   qt-components
Requires:   PackageKit >= 0.6.11
Requires:   PackageKit-libs >= 0.6.11
Requires:   PackageKit-zypp >= 0.6.11
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(packagekit-qt)
BuildRequires:  desktop-file-utils
Provides:   mg-package-manager > 0.2.2
Obsoletes:   mg-package-manager <= 0.2.2

%description
Package management UI for Nemo

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/mg-package-manager
%{_datadir}/applications/mg-package-manager.desktop
%{_datadir}/mg-package-manager/qml/*
%{_datadir}/pixmaps/mg-package-manager.png
# >> files
# << files
